Add controllers
Mobsman/java-shareit pull request #1
Opened 2022-07-20 20:35 UTC by Mobsman

Проверьте пожалуйста

2022-07-20 20:53 UTC, Mobsman commented
Проверьте пожалуйста

2022-07-21 05:23 UTC, EugeneLenkevich requested changes
Привет, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-07-21 05:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        Item i = getById(id);
i  - у нас обычно так называется счетчик циклов, пусть будет item :)

2022-07-21 05:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        Item i = getById(id);
i  - у нас обычно так называется счетчик циклов, пусть лучше будет что-то вроде origItem, oldItem и тп :)

2022-07-21 05:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        List<User> email = users.stream().filter(u -> u.getEmail().equals(user.getEmail())).collect(Collectors.toList());
А не лучше ли в сторедже создать соответствующий поисковый метод и всю логику поиска поместить в него? 
Так мы спрячем детали реализации. Допустим, потом у нас появится база данных, нам будет достаточно только переписать метод стореджа, а так продеться искать подобный код по всем сервисам :)

2022-07-21 09:02 UTC, Mobsman commented
Исправил

2022-07-21 09:34 UTC, EugeneLenkevich approved these changes
Все супер, спасибо!

2022-08-01 19:30 UTC, merged