commit
Mobsman/java-shareit pull request #6
Opened 2022-09-04 17:50 UTC by Mobsman

2022-09-04 19:29 UTC, Mobsman commented
Проверьте пожалуйста

2022-09-05 04:38 UTC, eugene-lenkevich requested changes
Привет, спасибо за PR

Все гут, единственное, а получится ли параметризовать классы-клиенты, чтобы они не возвращали Object, хотя бы один клиент переделать?

2022-09-05 04:44 UTC, eugene-lenkevich requested changes

2022-09-05 04:44 UTC, eugene-lenkevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    public Object addBooking(long userId, BookingRequest bookingRequest) {
Вот, например, тут возвращается Object, хотелось бы все таки параметризации :)  
Подобный класс-клиент часто является  частью API микросервиса, его, например, можно оформить  виде подключаемой библиотеки  и отдавать в другие сервисы чтобы дергать методы текущего.

2022-09-05 11:04 UTC, Mobsman commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    public Object addBooking(long userId, BookingRequest bookingRequest) {
Я пробовал. Но все упирается в родительский класс BaseClient который нам дали готовым и образец котроллера в котором возвращается Object. Если менять BaseClient полностью нужно переписывать.  https://github.com/yandex-praktikum/java-shareit/tree/add-docker/gateway/src/main/java/ru/practicum/shareit/booking

2022-09-05 11:33 UTC, eugene-lenkevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    public Object addBooking(long userId, BookingRequest bookingRequest) {
Ох, пардон, я туда и не посмотрел. 
Ладно, тогда ок, в целом все хорошо, получился какой то микросервис :)

PS: мало ли интересно будет есть еще вот такая часто используемая библиотека
https://habr.com/ru/post/485094/

см пункт про feign, работает аналогично спринговым репозиториям
 - декларативно

2022-09-05 11:34 UTC, eugene-lenkevich approved these changes

2022-10-09 15:38 UTC, merged